#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t specfem2d \
                         -C "start_jupyter -t -T @tool Simple_Specfem2D_Kernel.ipynb" \
                         -u anaconda-7 \
                         -r none
